import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateBankStatement = (transactions) => {
    const doc = new jsPDF();

    // --- Header Section ---
    // Logo / Brand Name
    doc.setFontSize(22);
    doc.setTextColor(16, 185, 129); // Emerald-500
    doc.text("ELITE", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("GYM MANAGEMENT SYSTEM", 14, 26);

    // Business Info (Right Aligned)
    const pageWidth = doc.internal.pageSize.width;
    doc.setFontSize(10);
    doc.setTextColor(50);
    doc.text("123 Fitness Blvd", pageWidth - 14, 20, { align: "right" });
    doc.text("New York, NY 10001", pageWidth - 14, 25, { align: "right" });
    doc.text(`Statement Date: ${new Date().toLocaleDateString()}`, pageWidth - 14, 30, { align: "right" });

    // --- Summary Section ---
    const totalCount = transactions.length;
    const netValue = transactions.reduce((sum, t) => sum + t.amount, 0);

    doc.setFillColor(243, 244, 246); // Gray-100
    doc.roundedRect(14, 40, pageWidth - 28, 25, 3, 3, "F");

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Total Selected Transactions", 24, 50);
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text(totalCount.toString(), 24, 58);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Net Value", 100, 50);
    doc.setFontSize(14);
    if (netValue >= 0) {
        doc.setTextColor(16, 185, 129); // Emerald-500
    } else {
        doc.setTextColor(220, 38, 38); // Red-600
    }
    doc.text(`$${netValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 100, 58);

    // --- Table Section ---
    const tableColumn = ["Date", "Description", "Category", "Method", "Status", "Amount"];
    const tableRows = transactions.map(t => {
        let amountFormatted = `$${Math.abs(t.amount).toFixed(2)}`;
        if (t.status === 'Completed') {
            amountFormatted = t.amount < 0 ? `-${amountFormatted}` : `+${amountFormatted}`;
        }

        // Status formatting logic for PDF text
        return [
            t.date,
            t.name,
            t.type,
            t.method,
            t.status,
            amountFormatted
        ];
    });

    autoTable(doc, {
        startY: 75,
        head: [tableColumn],
        body: tableRows,
        theme: 'plain',
        styles: {
            fontSize: 9,
            cellPadding: 3,
            textColor: 50,
            overflow: 'linebreak'
        },
        headStyles: {
            fillColor: [30, 41, 59], // Slate-800
            textColor: 255,
            fontStyle: 'bold'
        },
        columnStyles: {
            0: { cellWidth: 25 }, // Date
            1: { cellWidth: 'auto' }, // Description
            2: { cellWidth: 30 }, // Category
            3: { cellWidth: 30 }, // Method
            4: { cellWidth: 25 }, // Status
            5: { cellWidth: 30, halign: 'right', fontStyle: 'bold' } // Amount
        },
        didParseCell: function (data) {
            // Add custom coloring for specific cells if needed
            if (data.section === 'body' && data.column.index === 5) {
                const rawAmount = transactions[data.row.index].amount;
                const status = transactions[data.row.index].status;

                if (status === 'Failed') {
                    data.cell.styles.textColor = [156, 163, 175]; // Gray
                    data.cell.styles.fontStyle = 'italic';
                } else if (status === 'Pending') {
                    data.cell.styles.textColor = [245, 158, 11]; // Amber
                } else if (rawAmount < 0) {
                    data.cell.styles.textColor = [220, 38, 38]; // Red
                } else {
                    data.cell.styles.textColor = [16, 185, 129]; // Green
                }
            }
        }
    });

    // --- Footer Section ---
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Generated by Elite Management System • Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.height - 10, { align: "center" });
    }

    // Save the PDF
    doc.save(`Elite_Financial_Report_${new Date().toISOString().split('T')[0]}.pdf`);
};
